import type { Metadata } from "next";

import "./globals.css";
import { AppProviders } from "./providers";
import { ThemeToggle } from "./components/ThemeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`} suppressHydrationWarning>
      <body className="h-full flex flex-col font-sans">
        <AppProviders>
          <header className="w-full border-b border-border bg-card text-card-foreground p-4 top-0 z-50">
            <div className="max-w-5xl mx-auto flex items-center justify-between">
              <span className="font-bold tracking-tight text-lg text-primary">
                Form Wizard
              </span>
              <ThemeToggle />
            </div>
          </header>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
